[package]
name = "etag"
version = "1.0.2"
authors = ["Douman <douman@gmx.se>"]
description = "Simple ETag calculation implementation"
license = "MIT"
keywords = ["http", "etag"]

repository = "https://github.com/DoumanAsh/etag-rs"
documentation = "https://docs.rs/etag/"

readme = "README.md"
